#if ODIN_INSPECTOR && ENABLE_ODIN_INSPECTOR

using Sirenix.OdinInspector;

#endif

using System;
using System.Collections.Generic;
using Cysharp.Threading.Tasks;
using UnityEngine;
using Object = UnityEngine.Object;

namespace DGame
{
    internal partial class ResourceExtComponent : MonoBehaviour
    {
        public static ResourceExtComponent Instance { get; private set; }
        private readonly TimeoutController m_timeoutController = new TimeoutController();

        /// <summary>
        /// 正在加载的资源列表
        /// </summary>
        private readonly HashSet<string> m_loadingAssetList = new HashSet<string>();

        /// <summary>
        /// 检查是否可以释放资源时间间隔
        /// </summary>
        [SerializeField]
        private float checkCanReleaseInternal = 30f;
        private float m_checkCanReleaseTime = 0.0f;

        /// <summary>
        /// 对象池自动释放时间间隔
        /// </summary>
        [SerializeField]
        private float autoReleaseInternal = 0.0f;

        /// <summary>
        /// 保存加载的图片对象
        /// </summary>
#if ODIN_INSPECTOR && ENABLE_ODIN_INSPECTOR && UNITY_EDITOR
        [ShowInInspector, LabelText("保存加载的图片对象"), DisableInPlayMode]
#endif
        private LinkedList<LoadAssetObject> m_loadAssetObjectsLinkedList;

        /// <summary>
        /// 散图集合对象池
        /// </summary>
        private IObjectPool<AssetItemObject> m_assetItemPool;


#if UNITY_EDITOR
        public LinkedList<LoadAssetObject> LoadAssetObjectsLinkedList
        {
            get => m_loadAssetObjectsLinkedList;
            set => m_loadAssetObjectsLinkedList = value;
        }
#endif

        private async void Start()
        {
            Instance = this;
            await UniTask.Yield(PlayerLoopTiming.LastPostLateUpdate);
            IObjectPoolModule poolModule = ModuleSystem.GetModule<IObjectPoolModule>();
            m_assetItemPool = poolModule.CreateMultiSpawnObjectPool<AssetItemObject>("SetAssetPool",
                autoReleaseInternal, 16, 60, 0);
            m_loadAssetObjectsLinkedList = new LinkedList<LoadAssetObject>();
            InitializedResources();
        }

        private void Update()
        {
            m_checkCanReleaseTime += Time.unscaledDeltaTime;

            if (m_checkCanReleaseTime < (double)checkCanReleaseInternal)
            {
                return;
            }
            ReleaseUnused();
        }

#if ODIN_INSPECTOR && ENABLE_ODIN_INSPECTOR && UNITY_EDITOR
        [Button("释放无引用资源", ButtonHeight = 30)]
#endif
        public void ReleaseUnused()
        {
            if (m_loadAssetObjectsLinkedList == null)
            {
                return;
            }

            LinkedListNode<LoadAssetObject> current = m_loadAssetObjectsLinkedList.First;

            while (current != null)
            {
                var next = current.Next;
                if(current.Value.assetObject.IsCanRelease())
                {
                    m_assetItemPool.Recycle(current.Value.assetTarget);
                    MemoryPool.Recycle(current.Value.assetObject);
                    m_loadAssetObjectsLinkedList.Remove(current);
                }
                current = current.Next;
            }
            m_checkCanReleaseTime = 0.0f;
            // Debugger.Info("======== ResourceExtComponent.释放无引用资源 ========");
        }

        private void SetAsset(ISetAssetObject setAssetObject, Object assetObject)
        {
            m_loadAssetObjectsLinkedList.AddLast(new LoadAssetObject(setAssetObject, assetObject));
            setAssetObject.SetAsset(assetObject);
        }

        private async UniTask TryWaitingLoading(string assetObjectKey)
        {
            if (m_loadingAssetList.Contains(assetObjectKey))
            {
                try
                {
                    await UniTask.WaitUntil(
                            () => !m_loadingAssetList.Contains(assetObjectKey))
#if UNITY_EDITOR
                        .AttachExternalCancellation(m_timeoutController.Timeout(TimeSpan.FromSeconds(60)));
                    m_timeoutController.Reset();
#else
                    ;
#endif
                }
                catch (OperationCanceledException ex)
                {
                    if (m_timeoutController.IsTimeout())
                    {
                        Debugger.Error($"等待加载资源超时：{assetObjectKey}. 原因：{ex.Message}");
                    }
                }
            }
        }
    }
}